import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/hook/Navbar";
import React from 'react'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      {/* pause learning to redux toolkit */}

      <body className="bg min-h-screen" >
        <Navbar></Navbar>
        <div className="mt-32" >{children}</div>
      </body>
    </html>
  );
}
